<a href="https://colab.research.google.com/github/mehdiabbasidev/darsman-machine-learning/blob/main/RandomForestClassification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Dataset download link:
https://drive.google.com/file/d/1hr68gp-xFtD4lnuruFO_qNDz4mwf0IEU/view?usp=sharing

In [ ]:
from google.colab import drive
drive.mount('/content/drive/')

In [3]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.model_selection import train_test_split, GridSearchCV,RandomizedSearchCV
from sklearn.metrics import accuracy_score,confusion_matrix,recall_score,precision_score,classification_report,confusion_matrix
from sklearn.ensemble import RandomForestClassifier
%matplotlib inline

In [ ]:
path = '/content/drive/MyDrive/datasets/car_evaluation.csv'
df = pd.read_csv(path, header=None)
df.head()

In [38]:
col_names = ['buying', 'maint', 'doors', 'persons', 'lug_boot', 'safety', 'class']
df.columns = col_names
df.head()

buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc

In [53]:
df.shape
df.columns
df.dtypes
df.info()
df.nunique()
df['buying'].value_counts()
df.isnull().sum()

buying
vhigh    432
high     432
med      432
low      432
Name: count, dtype: int64

In [45]:
X = df.drop(['class'], axis=1)
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

In [ ]:
!pip install category_encoders

In [ ]:
import category_encoders as ce

ohe = ce.OneHotEncoder()
X_train_1 = ohe.fit_transform(X_train)
X_test_1 = ohe.transform(X_test)


oe = ce.OrdinalEncoder()
X_train_2 = oe.fit_transform(X_train)
X_test_2 = oe.transform(X_test)


be= ce.BinaryEncoder()
X_train_3 = be.fit_transform(X_train, y_train)
X_test_3 = be.transform(X_test)

In [59]:
import category_encoders as ce
oe = ce.OrdinalEncoder()
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)
X_train , X_test

buying  maint  doors  persons  lug_boot  safety
48         1      1      1        1         1       1
468        2      1      1        2         2       1
155        1      2      1        1         2       2
1721       3      3      2        1         2       2
1208       4      3      3        1         2       2
...      ...    ...    ...      ...       ...     ...
1130       4      4      1        1         1       2
1294       4      3      2        1         3       3
860        2      3      2        1         1       2
1459       3      2      4        3         2       3
1126       4      4      1        1         2       3

[1157 rows x 6 columns]

In [57]:
rfc = RandomForestClassifier(random_state=0)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)

print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))
print("accuracy_score:", accuracy_score(y_test, y_pred))
print("recall_score:", recall_score(y_test, y_pred,average='micro'))
print("precision_score:", precision_score(y_test, y_pred,average='micro'))
print(f"\nClassification Report:\n{classification_report(y_test, y_pred )}")

confusion_matrix:
 [[114   9   4   2]
 [  2  17   0   1]
 [  8   0 389   0]
 [  3   2   0  20]]
accuracy_score: 0.9457092819614711
recall_score: 0.9457092819614711
precision_score: 0.9457092819614711

Classification Report:
              precision    recall  f1-score   support

         acc       0.90      0.88      0.89       129
        good       0.61      0.85      0.71        20
       unacc       0.99      0.98      0.98       397
       vgood       0.87      0.80      0.83        25

    accuracy                           0.95       571
   macro avg       0.84      0.88      0.85       571
weighted avg       0.95      0.95      0.95       571



In [ ]:
rfc_100 = RandomForestClassifier(n_estimators=5, random_state=0)
rfc_100.fit(X_train, y_train)
y_pred_100 = rfc_100.predict(X_test)

print("confusion_matrix:\n", confusion_matrix(y_test, y_pred_100))
print("accuracy_score:", accuracy_score(y_test, y_pred_100))
print("recall_score:", recall_score(y_test, y_pred_100,average='micro'))
print("precision_score:", precision_score(y_test, y_pred_100,average='micro'))
print(f"\nClassification Report:\n{classification_report(y_test, y_pred_100 )}")

In [63]:
fi=rfc.feature_importances_
print(f"feature importances : {fi}")
print(f"sum of feature importances : {fi.sum()}")

feature_importances = pd.Series(data=fi, index=X.columns)
feature_importances=feature_importances.sort_values(ascending=False)
print(f"\nfeature_importances :\n{feature_importances}")

# feature_importances=pd.Series(data=rfc.feature_importances_, index=X.columns).sort_values(ascending=False)
# print(f"\nfeature_importances :\n{feature_importances}")


plt.figure(figsize=(8, 6))
colors = sns.color_palette('pastel', len(feature_importances))
feature_importances.plot(kind='bar', color=colors)
plt.title('Feature Importances', fontsize=16)
plt.xlabel('Features', fontsize=14)
plt.ylabel('Importance', fontsize=14)
plt.xticks(rotation=45, ha='right')
plt.grid(axis='y', linestyle='--', alpha=0.7)
plt.tight_layout()
plt.show()



feature_importances :
safety      0.295319
persons     0.233856
buying      0.151734
maint       0.146653
lug_boot    0.100048
doors       0.072389
dtype: float64


In [ ]:
X = df.drop(['class', 'doors'], axis=1)
y = df['class']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.33, random_state = 42)

oe = ce.OrdinalEncoder(cols=['buying', 'maint', 'persons', 'safety','lug_boot'])
X_train = oe.fit_transform(X_train)
X_test = oe.transform(X_test)

rfc = RandomForestClassifier(n_estimators=100,random_state=0)
rfc.fit(X_train, y_train)
y_pred = rfc.predict(X_test)

print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))
print("accuracy_score:", accuracy_score(y_test, y_pred))
print("recall_score:", recall_score(y_test, y_pred,average='micro'))
print("precision_score:", precision_score(y_test, y_pred,average='micro'))
print(f"\nClassification Report:\n{classification_report(y_test, y_pred )}")


print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))
cm = confusion_matrix(y_test, y_pred)
plt.figure(figsize=(8, 6))
sns.heatmap(cm, annot=True, fmt='d', cmap='Greens')
plt.xlabel('Predicted')
plt.ylabel('Actual')
plt.title('Confusion Matrix')
plt.show()

In [34]:
rf = RandomForestClassifier()

params = {
    'max_depth': [None, 10,15,20],
    'min_samples_split': [2, 5],
    'min_samples_leaf': [1, 2, 4],
}

random_search = RandomizedSearchCV(rf, params, n_iter=100, cv=5, verbose=1, n_jobs=-1, random_state=42)
random_search.fit(X_train, y_train)

print(f"Best parameters : {random_search.best_params_}")
best_rf = random_search.best_estimator_
y_pred = best_rf.predict(X_test)

print("confusion_matrix:\n", confusion_matrix(y_test, y_pred))
print("accuracy_score:", accuracy_score(y_test, y_pred))
print("recall_score:", recall_score(y_test, y_pred,average='micro'))
print("precision_score:", precision_score(y_test, y_pred,average='micro'))
print(f"\nClassification Report:\n{classification_report(y_test, y_pred )}")

Fitting 5 folds for each of 72 candidates, totalling 360 fits


/usr/local/lib/python3.10/dist-packages/sklearn/model_selection/_search.py:305: UserWarning: The total space of parameters 72 is smaller than n_iter=100. Running 72 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(


Best parameters : {'n_estimators': 50, 'min_samples_split': 2, 'min_samples_leaf': 4, 'max_depth': None}
confusion_matrix:
 [[ 91  13  16   9]
 [  4  10   0   6]
 [ 22   1 373   1]
 [  0  11   0  14]]
accuracy_score: 0.8546409807355516
recall_score: 0.8546409807355516
precision_score: 0.8546409807355516

Classification Report:
              precision    recall  f1-score   support

         acc       0.78      0.71      0.74       129
        good       0.29      0.50      0.36        20
       unacc       0.96      0.94      0.95       397
       vgood       0.47      0.56      0.51        25

    accuracy                           0.85       571
   macro avg       0.62      0.68      0.64       571
weighted avg       0.87      0.85      0.86       571

